// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type File struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	FileID string `json:"fileID"`
}

type Image struct {
	ID      string   `json:"id"`
	Project *Project `json:"project"`
	File    *File    `json:"file"`
}

type NewImage struct {
	ProjectID string `json:"projectID"`
	FileID    string `json:"fileID"`
}

type NewProject struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UploadFile struct {
	ID   string         `json:"id"`
	File graphql.Upload `json:"file"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
