basePath: /
host: localhost:3000
info:
  contact:
    email: rainforestnick@gmail.com
    name: Rainforest
    url: http://rainforest.tools
  title: Rainforest Personal Backend
  version: "0.1"
paths:
  /about:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: About
  /health:
    get:
      summary: Show the status of server
swagger: "2.0"
